import './globals.css';

import NextAuthProvider from '~/context/nextauth-provider';
import { ThemeProvider } from '~/context/theme-provider';
import { heebo } from '~/fonts/fonts';
import TRPCProvider from '~/trpc/trpc-provider';

import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Setara Biru',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={heebo.className}>
        <NextAuthProvider>
          <TRPCProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
            >
              {children}
            </ThemeProvider>
          </TRPCProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
