import './globals.css';

import { Inter } from 'next/font/google';
import NextAuthProvider from '~/context/nextauth-provider';
import { ThemeProvider } from '~/context/theme-provider';

import TRPCProvider from './_trpc/trpc-provider';

import type { Metadata } from 'next';
const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Setara Biru',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <NextAuthProvider>
          <TRPCProvider>
            <ThemeProvider
              attribute='class'
              defaultTheme='light'
            >
              {children}
            </ThemeProvider>
          </TRPCProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
